name: stsci.skypac
dependencies:
  - "python>=3.5"
  - numpy
  - "astropy>=3.1"
  - numpydoc
  - graphviz
  - matplotlib
  - stsci.imagestats
  - stsci.tools
  - stwcs
  - spherical-geometry
  - sphinx
  - pip:
    - sphinx_rtd_theme
    - git+https://github.com/spacetelescope/stsci_rtd_theme.git#egg=stsci_rtd_theme
